# Generated by Django 6.0.5 on 2026-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='Paste an image URL', max_length=500, null=True)),
                ('technologies', models.CharField(help_text='Comma-separated technologies (e.g., Django, MySQL, CSS)', max_length=250)),
                ('project_url', models.URLField(blank=True, max_length=500, verbose_name='Live Demo URL')),
                ('github_url', models.URLField(blank=True, max_length=500, verbose_name='GitHub Repository URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools & Others')], max_length=20)),
                ('proficiency', models.IntegerField(help_text='Proficiency percentage (0-100)')),
                ('icon_class', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fab fa-html5')", max_length=50)),
            ],
        ),
    ]
